---
resource_types:
- name: github-tags
  type: docker-image
  source:
    repository: ecsteam/github-tags-resource
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: source
  type: git
  source:
    uri: git@github.com:ECSTeam/spring-boot-docker-image.git
    private_key: {{github-private-key}}
- name: spring-boot
  type: github-tags
  source:
    user: spring-projects
    repository: spring-boot
    access_token: {{github-access-token}}
- name: docker-hub
  type: docker-image
  source:
    repository: ecsteam/spring-boot
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
- name: notify
  type: slack-notification
  source:
    url: {{slack-webhook-url}}

jobs:
- name: generate-project
  public: true
  plan:
  - aggregate:
    - get: spring-boot
      trigger: true
    - get: source
      trigger: true
  - task: spring-initializr
    file: source/ci/generate-project.yml
  - put: docker-hub
    params:
      build: boot-project
      tag: spring-boot/tag
      tag_as_latest: true
  on_failure:
    do:
    - put: notify
      params:
        channel: "#topic-pipeline-alerts"
        username: concourse
        text: |
          :thumbsdown: Job $BUILD_JOB_NAME failed!

          Job details: <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME>

  on_success: 
    do:
    - put: notify
      params:
        channel: "#topic-pipeline-alerts"
        username: concourse
        text_file: version/number
        text: |
          :thumbsup: A new version of $BUILD_JOB_NAME has been built.

          Release: <https://github.com/ECSTeam/$BUILD_JOB_NAME/releases/v$TEXT_FILE_CONTENT>
          Job: <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME>
